### ISSUE TITLE
missing 1 required positional argument: 'profile'

### ISSUE THREAD

**Issue by Alinavost** [Koozco/pmp#45]
Hi! :) 
I'm trying to run the experiment.py in the examples section, and encountering this error:

```
   return self.rule.find_committee(self.k, profile)
TypeError: find_committee() missing 1 required positional argument: 'profile'
```

I didn't change anything. Can you please help and clarify which argument I should add and where for it to run?

Thanks a lot!! :)

**Comment by scherven** [comment]
How did you resolve this issue?

**Comment by Alinavost** [comment]
Hi,
I didn't solve it, so if you find a way please let me know :)
